[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"   # or the Node you use locally

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200